/* build.rs
 *
 * Copyright 2026 Sébastien Le Callonnec
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 */

fn main() {
    glib_build_tools::compile_resources(&["src"], "src/nutmeg.gresource.xml", "nutmeg.gresource");

    // Ensure config.rs exists (normally generated by Meson, but necessary for bare cargo builds)
    let config_path = std::path::Path::new("src/config.rs");
    if !config_path.exists() {
        if let Ok(config_in) = std::fs::read_to_string("src/config.rs.in") {
            let version =
                std::env::var("CARGO_PKG_VERSION").unwrap_or_else(|_| "0.1.0".to_string());
            let pkg_name = std::env::var("CARGO_PKG_NAME").unwrap_or_else(|_| "nutmeg".to_string());

            let config_out = config_in
                .replace("@VERSION@", &format!("\"{}\"", version))
                .replace("@GETTEXT_PACKAGE@", &format!("\"{}\"", pkg_name))
                .replace("@LOCALEDIR@", "\"/usr/local/share/locale\"")
                .replace(
                    "@PKGDATADIR@",
                    &format!("\"/usr/local/share/{}\"", pkg_name),
                );
            let _ = std::fs::write("src/config.rs", config_out);
        }
    }

    // Attempt to load .env file manually to bake compile-time secrets
    // into the binary via `option_env!` (e.g. for Flatpak isolated builds).
    if let Ok(content) = std::fs::read_to_string(".env") {
        for line in content.lines() {
            let line = line.trim();
            if line.is_empty() || line.starts_with('#') {
                continue;
            }
            if let Some((key, value)) = line.split_once('=') {
                let key = key.trim();
                let value = value.trim().trim_matches('"').trim_matches('\'');
                println!("cargo:rustc-env={}={}", key, value);
            }
        }
    }
}
