CREATE TABLE players (
    id INTEGER PRIMARY KEY NOT NULL,
    team_id INTEGER NOT NULL,
    first_name TEXT NOT NULL,
    nick_name TEXT,
    last_name TEXT NOT NULL,
    player_number INTEGER NOT NULL,
    age INTEGER NOT NULL,
    age_days INTEGER,
    tsi INTEGER NOT NULL,
    player_form INTEGER NOT NULL,
    statement TEXT,
    experience INTEGER NOT NULL,
    loyalty INTEGER NOT NULL,
    mother_club_bonus BOOLEAN NOT NULL,
    leadership INTEGER NOT NULL,
    salary INTEGER NOT NULL,
    is_abroad BOOLEAN NOT NULL,
    agreeability INTEGER NOT NULL,
    aggressiveness INTEGER NOT NULL,
    honesty INTEGER NOT NULL,
    league_goals INTEGER,
    cup_goals INTEGER,
    friendlies_goals INTEGER,
    career_goals INTEGER,
    career_hattricks INTEGER,
    speciality INTEGER,
    transfer_listed BOOLEAN NOT NULL,
    national_team_id INTEGER,
    country_id INTEGER NOT NULL,
    caps INTEGER,
    caps_u20 INTEGER,
    cards INTEGER,
    injury_level INTEGER,
    sticker TEXT,
    FOREIGN KEY (team_id) REFERENCES teams(id)
);
