ALTER TABLE players ADD COLUMN gender_id INTEGER NOT NULL DEFAULT 1;
ALTER TABLE teams ADD COLUMN gender_id INTEGER NOT NULL DEFAULT 1;
ALTER TABLE leagues ADD COLUMN league_system_id INTEGER NOT NULL DEFAULT 1;
