-- Drop new tables
DROP TABLE IF EXISTS downloads;
DROP TABLE IF EXISTS players;
DROP TABLE IF EXISTS teams;

-- Restore old teams table (simplified schema from memory/best effort)
CREATE TABLE teams (
    id INTEGER PRIMARY KEY NOT NULL,
    user_id INTEGER,
    name TEXT NOT NULL,
    raw_data TEXT NOT NULL,
    short_name TEXT,
    is_primary_club BOOLEAN,
    founded_date TEXT,
    arena_id INTEGER,
    arena_name TEXT,
    league_id INTEGER,
    league_name TEXT,
    country_id INTEGER,
    country_name TEXT,
    region_id INTEGER,
    region_name TEXT,
    homepage TEXT,
    dress_uri TEXT,
    dress_alternate_uri TEXT,
    logo_url TEXT,
    trainer_id INTEGER,
    cup_still_in BOOLEAN,
    cup_id INTEGER,
    cup_name TEXT,
    cup_league_level INTEGER,
    cup_level INTEGER,
    cup_level_index INTEGER,
    cup_match_round INTEGER,
    cup_match_rounds_left INTEGER,
    power_rating_global INTEGER,
    power_rating_league INTEGER,
    power_rating_region INTEGER,
    power_rating_indiv INTEGER,
    friendly_team_id INTEGER,
    league_level_unit_id INTEGER,
    league_level_unit_name TEXT,
    league_level INTEGER,
    number_of_victories INTEGER,
    number_of_undefeated INTEGER,
    number_of_visits INTEGER,
    team_rank INTEGER,
    fanclub_id INTEGER,
    fanclub_name TEXT,
    fanclub_size INTEGER,
    color_background TEXT,
    color_primary TEXT,
    is_bot BOOLEAN,
    bot_since TEXT,
    youth_team_id INTEGER,
    youth_team_name TEXT
);

-- Restore old players table
CREATE TABLE players (
    id INTEGER PRIMARY KEY NOT NULL,
    team_id INTEGER NOT NULL,
    first_name TEXT NOT NULL,
    last_name TEXT NOT NULL,
    player_number INTEGER NOT NULL,
    age INTEGER NOT NULL,
    age_days INTEGER,
    tsi INTEGER NOT NULL,
    player_form INTEGER NOT NULL,
    statement TEXT,
    experience INTEGER NOT NULL,
    loyalty INTEGER NOT NULL,
    mother_club_bonus BOOLEAN NOT NULL,
    leadership INTEGER NOT NULL,
    salary INTEGER NOT NULL,
    is_abroad BOOLEAN NOT NULL,
    agreeability INTEGER NOT NULL,
    aggressiveness INTEGER NOT NULL,
    honesty INTEGER NOT NULL,
    league_goals INTEGER,
    cup_goals INTEGER,
    friendlies_goals INTEGER,
    career_goals INTEGER,
    career_hattricks INTEGER,
    speciality INTEGER,
    transfer_listed BOOLEAN NOT NULL,
    national_team_id INTEGER,
    country_id INTEGER NOT NULL,
    caps INTEGER,
    caps_u20 INTEGER,
    cards INTEGER,
    injury_level INTEGER,
    sticker TEXT,
    FOREIGN KEY (team_id) REFERENCES teams(id)
);
