-- Create downloads table
CREATE TABLE downloads (
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    timestamp TEXT NOT NULL,
    status TEXT NOT NULL
);

-- Recreate Teams with download_id
DROP TABLE IF EXISTS teams;
CREATE TABLE teams (
    id INTEGER NOT NULL,
    download_id INTEGER NOT NULL,
    user_id INTEGER,
    name TEXT NOT NULL,
    raw_data TEXT NOT NULL,
    short_name TEXT,
    is_primary_club BOOLEAN,
    founded_date TEXT,
    arena_id INTEGER,
    arena_name TEXT,
    league_id INTEGER,
    league_name TEXT,
    country_id INTEGER,
    country_name TEXT,
    region_id INTEGER,
    region_name TEXT,
    homepage TEXT,
    dress_uri TEXT,
    dress_alternate_uri TEXT,
    logo_url TEXT,
    trainer_id INTEGER,
    cup_still_in BOOLEAN,
    cup_id INTEGER,
    cup_name TEXT,
    cup_league_level INTEGER,
    cup_level INTEGER,
    cup_level_index INTEGER,
    cup_match_round INTEGER,
    cup_match_rounds_left INTEGER,
    power_rating_global INTEGER,
    power_rating_league INTEGER,
    power_rating_region INTEGER,
    power_rating_indiv INTEGER,
    friendly_team_id INTEGER,
    league_level_unit_id INTEGER,
    league_level_unit_name TEXT,
    league_level INTEGER,
    number_of_victories INTEGER,
    number_of_undefeated INTEGER,
    number_of_visits INTEGER,
    team_rank INTEGER,
    fanclub_id INTEGER,
    fanclub_name TEXT,
    fanclub_size INTEGER,
    color_background TEXT,
    color_primary TEXT,
    is_bot BOOLEAN,
    bot_since TEXT,
    youth_team_id INTEGER,
    youth_team_name TEXT,
    PRIMARY KEY (id, download_id),
    FOREIGN KEY (download_id) REFERENCES downloads(id) ON DELETE CASCADE
);

-- Recreate Players with download_id and new fields
DROP TABLE IF EXISTS players;
CREATE TABLE players (
    id INTEGER NOT NULL,
    download_id INTEGER NOT NULL,
    team_id INTEGER NOT NULL,
    first_name TEXT NOT NULL,
    last_name TEXT NOT NULL,
    player_number INTEGER NOT NULL,
    age INTEGER NOT NULL,
    age_days INTEGER,
    tsi INTEGER NOT NULL,
    player_form INTEGER NOT NULL,
    statement TEXT,
    experience INTEGER NOT NULL,
    loyalty INTEGER NOT NULL,
    mother_club_bonus BOOLEAN NOT NULL,
    leadership INTEGER NOT NULL,
    salary INTEGER NOT NULL,
    is_abroad BOOLEAN NOT NULL,
    agreeability INTEGER NOT NULL,
    aggressiveness INTEGER NOT NULL,
    honesty INTEGER NOT NULL,
    league_goals INTEGER,
    cup_goals INTEGER,
    friendlies_goals INTEGER,
    career_goals INTEGER,
    career_hattricks INTEGER,
    speciality INTEGER,
    transfer_listed BOOLEAN NOT NULL,
    national_team_id INTEGER,
    country_id INTEGER NOT NULL,
    caps INTEGER,
    caps_u20 INTEGER,
    cards INTEGER,
    injury_level INTEGER,
    sticker TEXT,
    -- Skills
    stamina_skill INTEGER,
    keeper_skill INTEGER,
    playmaker_skill INTEGER,
    scorer_skill INTEGER,
    passing_skill INTEGER,
    winger_skill INTEGER,
    defender_skill INTEGER,
    set_pieces_skill INTEGER,
    -- Last Match
    last_match_date TEXT,
    last_match_id INTEGER,
    last_match_position_code INTEGER,
    last_match_played_minutes INTEGER,
    last_match_rating INTEGER,
    last_match_rating_end_of_match INTEGER,

    PRIMARY KEY (id, download_id),
    FOREIGN KEY (download_id) REFERENCES downloads(id) ON DELETE CASCADE,
    FOREIGN KEY (team_id, download_id) REFERENCES teams(id, download_id) ON DELETE CASCADE
);
